openapi: 3.0.0
info:
  title: SiloDispatch API
  version: 1.0.0
  description: API specification for SiloDispatch Delivery Management System
paths:
  # TODO: Add endpoints for orders, batches, OTP, payment, settlement 